### ISSUE TITLE
win7

### ISSUE THREAD

**Issue by peekaa** [Disassembler0/Win10-Initial-Setup-Script#10]
Is there anything like this for win7? Which parts of this can we use for  win7? Thank you.

**Comment by Disassembler0** [comment]
Since I'm not supporting even old builds of Win10, I'm definitely not planning to support Win7 or 8. I have no idea if there is anything like this for Win7, but they are out for nearly 8 years, so I'm pretty sure there are various tools and tweakers with equivalent functionality.

Not many tweaks from my script will work also on Win7, but I'm 99% sure that following will:
- Disable error reporting
- Lower UAC
- Enable sharing mapped drives
- Disable implicit administrative shares
- Disable Firewall
- Disable MSRT offering via WU
- Disable driver offering via WU
- Disable Home Groups
- Disable Remote Asistance
- Enable Remote Desktop
- Disable Automplay
- Disable AutoRun
- Set BIOS time to UTC
- Disable Sticky keys
- Show small icons in Task bar
- Show known file extensions
- Show hidden files
- Show This PC on desktop
- Set DEP to OptOut

I haven't tested it, though, and I'm not even planning to, so feel free to fork and adjust yourself.
