### ISSUE TITLE
UnpinStartMenuTiles not working on Windows Server 2016

### ISSUE THREAD

**Issue by Zero3** [Disassembler0/Win10-Initial-Setup-Script#100]
I ran the script, including `UnpinStartMenuTiles` on a fully patched Windows Server 2016 Standard and rebooted. But the tiles are still there:

![image](https://user-images.githubusercontent.com/82504/40127876-aa3a2816-5930-11e8-83b1-0a961a0b884b.png)

**Comment by Disassembler0** [comment]
Hi,
Which build do you have? The tweak works only on 1703, 1709 and 1803. I suspect you're subscribed for LTSC, so you still have 1607 (RS1 / build 14393).

Previously the tiles were in EDB database and there were many problems associated with its modification (see #8), so that's why this tweaks works only on versions where Microsoft decided to use different tile store.

**Comment by Zero3** [comment]
@Disassembler0 Aha! The server is indeed running version 1607.

I did not see any information in the script comments about version requirements for this tweak, so I assumed that it was a bug when nothing happened. Thanks for looking into it. I will close this issue.
