### ISSUE TITLE
Third party apps not being uninstalled

### ISSUE THREAD

**Issue by ryandcci** [Disassembler0/Win10-Initial-Setup-Script#101]
I have noticed that on some clean installs of 1709 and 1803 your script will not uninstall the third party apps because they are not actually installed. The entries in the start menu are just shortcuts. You then have to go through and click each one so that they will download/install via the store. Once they are installed the script can remove them without issue.

Is there some way to add a function to the script that will check if the apps are actually installed, and force to install if they are not?

**Comment by Disassembler0** [comment]
> Is there some way to add a function to the script that will check if the apps are actually installed, and force to install if they are not?

Not that I would know of. There are different channels through which the apps can be loaded. Generally it should be enough to apply `DisableAppSuggestions` and `UnpinStartMenuTiles` but sometimes you might not be fast enough, so the tiles and app data load right after first launch, before you manage to apply the tweaks. Some of the apps may be even already provisioned in your image based on language and edition.

I did some research some time ago in #8, but I haven't been poking into it ever since, so it's possible that the things around tile store and provisioned apps changed and it'll be now easier to get rid of them. I wouldn't bet on that, though.

**Comment by Tikus** [comment]
To prevent those application from installing it must be disabled before user logs in for the first time by setting properties in Default user's registry in C:\Users\Default\NTUSER.DAT under

SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
- PreInstalledAppsEnabled
- OemPreInstalledAppsEnabled

This is the reason why im running this script for default user by mounting his registry and applying all tweaks there so when i create new users on workstation all those tweaks are already there including custom start menu like 
`Import-StartLayout -LayoutPath "C:\temp\DefaultLayout.xml" -MountPath "C:\"`

 which eliminates empty icons of applications that are not installing.

Im trying to implement this in my fork where i added option -useDefaultUser that allows writing tweaks to C:\Users\Default\NTUSER.DAT instead of user's hive that is running the script. 

Not sure if this is still valid for new build but i was reading about this in this post:
https://blog.danic.net/how-windows-10-pro-installs-unwanted-apps-candy-crush-and-how-you-stop-it/

**Comment by kroimon** [comment]
I also want to use the script in a domain environment, so it would really be great to have some kind of feature to apply settings to the default user's registry hive...

I'm working on custom script parts for that, but having something like that integrated would be awesome!

**Comment by Qrzysio** [comment]
I also face this issue and I would like to share with you with a few examples.

Afer fresh install of Windows 10 (1803) yesterday, I run "Win10-Initial-Setup-Script" and noticed that a few apps left. I had to uninstall them manually from "Apps and features" or through the start menu. 

So there are three games called: 
- Candy Crush Saga (king.com), 
- Cooking Fever (Nordcurrent), 
- Dragon Mania Legends (Gameloft.)

![image](https://user-images.githubusercontent.com/13356480/43648914-089fc6ba-973c-11e8-8d09-8d88fc0664d5.png)

and "Xbox gaming overlay", which cannot be uninstalled.

![image](https://user-images.githubusercontent.com/13356480/43648955-2448fcf6-973c-11e8-95b9-c1dea04a49df.png)

Hopefully, someone will find a way to remove these items.

**Comment by jtbwatson** [comment]
I did what the above user did and installed several of them then ran the script. At that point I was able to successfully get rid of them with the script. It is frustrating...

**Comment by Disassembler0** [comment]
I'm afraid there isn't much what I can do to stop the bloatware tidal wave using the script. There is a provisioning process which launches immediately on the first login or immediately after the machine comes up online, so the only place where you could reliably get rid of it is the sysprep process, which involves modification of installation media.

Once the provisioning begins, it needs to finish for the script to work well. If you run it in few minutes after the first login, the applications are not yet installed by the provisioning and since they are not installed yet, the script can't remove them. That's why some of the apps pop up even after you run the script. On top of that, Microsoft relentlessly adds new and new applications to be pushed onto your devices, so it's entirely possible that some application are not yet covered by the script (in which case feel free to open an issue, or better yet, a PR).

For the new users on a computer where the admin account has already been set and logged in at least once, the approach which @Tikus suggests works the best. But I'm reluctant to do anything with the Default user's registry in the script as many keys and settings don't exist there are are populated (and some even reset) on the first login, so you will end up re-applying the script after login anyway.

So just for the sake of this issue, following PowerShell script disables all the suggestions and online provisioning for the Default user and all new users created afterwards. Needs to be run as admin.
```powershell
# Load the Default user's hive
reg load HKLM\DefaultUser "$env:systemDrive\Users\Default\NTUSER.DAT" | Out-Null
New-PSDrive -Name HKCDU -PSProvider Registry -Root HKLM\DefaultUser | Out-Null

Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "ContentDeliveryAllowed" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "OemPreInstalledAppsEnabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "PreInstalledAppsEnabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "PreInstalledAppsEverEnabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SilentInstalledAppsEnabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-310093Enabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338387Enabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338388Enabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338389Enabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338393Enabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-353698Enabled" -Type DWord -Value 0
Set-ItemProperty -Path "HKCDU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SystemPaneSuggestionsEnabled" -Type DWord -Value 0

# Unload the Default user's hive
reg unload HKLM\DefaultUser | Out-Null
```

---

@Tikus: I've seen your `-useDefaultUser` and have a suggestion/improvement for you. You can do basically this:
```powershell
reg load HKLM\DefaultUser "$env:systemDrive\Users\Default\NTUSER.DAT"
Remove-PSDrive HKCU
New-PSDrive -Name HKCU -PSProvider Registry -Root HKLM\DefaultUser
```
That way you can still use `HKCU` instead of your newly introduced `USERHIVE` and the tweaks remain copy-pastable. If the `-useDefaultUser` flag is set, then the meaning of `HKCU` will be different, but only in the context of that single instance of the script run.
