### ISSUE TITLE
Great job man! Have you thought about integrating this with boxstarter?

### ISSUE THREAD

**Issue by thedonquixotic** [Disassembler0/Win10-Initial-Setup-Script#120]
Have you thought about integrating this with boxstarter and chocolatey? https://github.com/Microsoft/windows-dev-box-setup-scripts

I actually might take my current boxstarter script and adjust my settings etc to fit your formatting etc so that it's easier to enable and disable comments using the commenting syntax you've used. Might put that up as a fork or something to yours though not sure yet.

**Comment by Disassembler0** [comment]
There were already some discussions about Chocolatey in #23 and #52, plus the FAQ question "*I'm using a tweak for \<feature> on my installation, can you add it?*" explicitly mentions it. I have never heard about Boxstarter, but from the documentation it seems that [the parts where our projects are overlapping](https://boxstarter.org/WinConfig) are marginal.

The most effortless way to integrate *Win10-Initial-Setup-Script* with virtually any package or automation manager is to simply download it along with a preset from your own repository and run. Something like
```
Invoke-WebRequest https://raw.githubusercontent.com/Disassembler0/Win10-Initial-Setup-Script/master/Win10.ps1
Invoke-WebRequest https://some.path.to/my.preset
powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 -Preset my.preset
```

Other than that, I don't see how the script can easily be integrated with anything, especially when it's aimed to be initially run long before any other software is installed (can even be as part of sysprep).

So if you wish, feel free to fork and adjust to your liking, but I'm not planning to add support for any 3rd party management tools.

**Comment by thedonquixotic** [comment]
@Disassembler0 Totally reasonable. The purpose of Boxstarter is also sysprep but it adds additional functionality to plain powershell from my understanding, such as the ability to bootstrap and skip through program installation stuff. 

One quick question though about your script. 

You have the tweaks set up like this:

/#EnableFeature,        /#DisableFeature,

If I uncomment the Disable it is still line commented by the EnableFeature. Is the intention that in order to disable features one should uncomment both? So that it runs the Enable and then Disables it right afterwards? I could guess that you might do that because it would create a consistent toggling between the settings etc? Just wanted to check though.

**Comment by Disassembler0** [comment]
If you're referring to the `$tweaks` array in the beginning of the script, then the `#DisableFeature` (and basically the whole second and for some tweaks also the third column) is there just to have a quick overview about the possibilities and to see what tweak needs to be run if one wishes to revert whatever `EnableFeature` did, without having to scroll several hundreds lines down to see how's the reversal tweak actually called and if there is even one.

Usually you don't need to revert or reapply all the tweaks, so instead of rerunning the whole script with `DisableFeature` uncommented, you pass it as command line argument
```
powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 DisableFeature
```
For more info about command line arguments, refer to chapter [Advanced usage](https://github.com/Disassembler0/Win10-Initial-Setup-Script#advanced-usage) in README. There will be [some changes](https://github.com/Disassembler0/Win10-Initial-Setup-Script/tree/includes#advanced-usage) in near future when I free myself from other duties.

**Comment by Disassembler0** [comment]
And yes, your assumption about consistent toggling is correct, so you could use both tweaks at the same time. But like I wrote above, there are cleaner ways to revert something.

**Comment by thedonquixotic** [comment]
Cool, thanks!
