### ISSUE TITLE
Making Install and Uninstall Apps more deep

### ISSUE THREAD

**Issue by cyberpunkbln** [Disassembler0/Win10-Initial-Setup-Script#130]
Hello,

i want to bring this functions in function;).
```

# Uninstall WindowsApp
Function UninstallWindowsApp($AppName)
{
	If ($AppName)
	{
		Write-Output "Uninstalling $AppName ..."
		#Get-AppxPackage "$AppName" | Remove-AppxPackage
	}
}

# Install WindowsApp
Function InstallWindowsApp($AppName)
{
	If ($AppName)
	{
		Write-Output "Installing $AppName ..."
		#Get-AppxPackage -AllUsers "$AppName" | ForEach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
	}
}
```

Knows anybody how can i tweak this script that i can render up some options for the -preset and for the direct function call.

.\Win10Cmd.cmd RequestAdmin InstallWindowsApp WaitForKey

default.preset

InstallWindowsApp[App] or some other.

thx will be made this script more deep;)

**Comment by Disassembler0** [comment]
That would require some rework of the argument parser which I'm not really keen on doing. There currently aren't any functions which would accept parameters and installation/uninstallation of apps is probably the only tweak which would benefit from such change. But then again, if you would want to uninstall *all* apps, as most of the people do, you would need to have some wrappers for it anyway, because you probably wouldn't want to maintain ~75 extra lines in preset just because of that.

However version 3.0 released today allows for implementation of custom tweaks, so you can have custom tweaks for the uninstallation and group the apps based on whatever criteria fits you. So you can have e.g. a file called `mytweaks.psm1` with following content

```powershell
Function UninstallGames {
    $games = @(
        "king.com.BubbleWitch3Saga",
        "king.com.CandyCrushSodaSaga",
        "king.com.CandyCrushSaga"
    )

    ForEach ($app in $games) {
        Get-AppxPackage -Name $app | Remove-AppxPackage
    }
}
```

And they you just add `UninstallGames` to your preset and run the script as

```
powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 -include Win10.psm1 -include mytweaks.psm1 -preset yourpreset.preset
```
