### ISSUE TITLE
Suggestion: L2TP Transverse NAT enable

### ISSUE THREAD

**Issue by LiBOSS-CZ** [Disassembler0/Win10-Initial-Setup-Script#151]
Add possibility to enable L2TP secure connection for stations behind NAT.

https://support.microsoft.com/en-us/help/926179/how-to-configure-an-l2tp-ipsec-server-behind-a-nat-t-device-in-windows

**Comment by Disassembler0** [comment]
```powershell
Function EnableIPSecBehindNAT {
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\PolicyAgent" -Name "AssumeUDPEncapsulationContextOnSendRule" -Type Dword -Value 2
}
```

Feel free to add it to you custom tweak library. I'm not gonna add it because this is really for a narrow group of users and should be handled by domain GPO rather than some shady script on the internet.

I'm running IPSec server behind NAT on Win2012 and don't recall setting this. And I even have road warrior profiles. I have to check how I did that. :)
