### ISSUE TITLE
DisableActivityHistory causes Windows Shell to restart

### ISSUE THREAD

**Issue by gnarum** [Disassembler0/Win10-Initial-Setup-Script#170]
**OS:** Windows 10 Pro v1803 (fully updated till 10th of Nov)

**Context:**
After a fresh install and fully updating W10, I ran a custom preset of rules, which can be found below.

**Issue:**
Using the 3-fingers gesture for Multitasking view causes Windows Shell to restart.

**Temporary fix:**
After running EnableActivityHistory the gesture worked again as intended, without any crash.

**My custom preset**
**Privacy Tweaks**
DisableTelemetry
DisableWiFiSense
DisableWebSearch
DisableActivityHistory
DisableAppSuggestions
DisableLocationTracking
DisableMapUpdates
DisableFeedback
DisableTailoredExperiences
DisableAdvertisingID
DisableWebLangList
DisableCortana
DisableErrorReporting
DisableDiagTrack
DisableWAPPush
HideRecentJumplists

**Security Tweaks**
EnableDotNetStrongCrypto
DisableAdminShares
SetDEPOptOut

**Services Tweaks**
DisableSharedExperiences
DisableRemoteAssistance
DisableAutoplay
DisableAutorun

**Application Tweaks**
DisableOneDrive
UninstallOneDrive
UninstallMsftBloat
UninstallThirdPartyBloat
DisableXboxFeatures
DisableAdobeFlash
UninstallXPSPrinter
RemoveFaxPrinter

**Aux Functions**
WaitForKey
Restart

**Comment by Disassembler0** [comment]
Did you use recent version of the script? Version 3.3 or 3.2 after commit 08ce664a37589bfc3cb1f6872dc994a80b9938dd. There were some changes related to `DisableActivityHistory` discussed in #149.

Since I don't have any touchy-feely device at the moment, can you please run just following snippet as admin, reboot and see if the issue reapper?

```
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "EnableActivityFeed" -Type DWord -Value 0
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities" -Type DWord -Value 0
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities" -Type DWord -Value 0
```

If it does, you can fix it by reapplying `EnableActivityHistory` again. If it'll be OK, then the disabled user service (which was the addition in 08ce664a37589bfc3cb1f6872dc994a80b9938dd) will likely be the culprit.

**Comment by gnarum** [comment]
I used v3.3. Forgot to include that somewhat important part..
The culprit does seem to be the disabled user service, as after running the snippet and rebooting, the swipe action works fine.

Thank you very much!
