### ISSUE TITLE
Can't open Calculator App, or install .appx packages

### ISSUE THREAD

**Issue by tryptc** [Disassembler0/Win10-Initial-Setup-Script#177]
Like the title says, I cannot open the calculator App, or install .appx packages.

I'm sorry I've been bothering you with issues. Your quick response is very admirable.

Is it possible to donate to you?

**Comment by Disassembler0** [comment]
What message are you getting (if any) or what does it do when you attempt to open the calculator or install appx?
Which Windows build do you use?
Are you using custom preset or any custom tweaks or just the default?

**Comment by tryptc** [comment]
For the calculator: "You'll need a new app to open this calculator"

For the appx: "Windows can't open this type of file(appx)    Try an app on this PC"

**Comment by Disassembler0** [comment]
I haven't been able to replicate the problem and I have been trying pretty hard to break as many things as possible. I'm 99% sure this wasn't caused by the script. The message about appx suggests that you're missing Store and DesktopAppInstaller (either the whole applications or just the associations), which might be caused by `UninstallWindowsStore` tweak, but that tweak is not included in the default preset. About the calculator I have no clue at all. Looks like corrupted cache or again missing some associations.

Take a look here - https://appuals.com/fix-youll-need-new-app-open-calculator/ . Maybe whatever helps to fix the calculator will help the other problem too.

**Comment by hlarrymorepremera** [comment]
No matter how many times I restarted the PC after following the directions, I wasn't able to double-click and install the .appx file (even after troubleshooting Store).  So, I decided to download 7-Zip, rename the file with the 7.z extension (didn't really need to rename it), then unzipped the package into a directory and ran the .exe file in the base of the newly created dir, and achieved my goal.  

Like .cab and other package files, the .appx files can be unpackaged.
