### ISSUE TITLE
No audio when SetVisualFXAppearance is enabled

### ISSUE THREAD

**Issue by murillow** [Disassembler0/Win10-Initial-Setup-Script#182]
First, I enabled `SetVisualFXPerformance` upon installing Windows and the audio was fine. After that, I enabled `SetVisualFXAppearance` to go back to the original Windows animations. But when I restarted Windows, the audio was not working. To solve it and get the audio working again, I had to switch back to `SetVisualFXPerformance`.

**Comment by Disassembler0** [comment]
I can't replicate the problem. Can you please elaborate a bit more on *the audio was not working*? How did it look like? Did you see a playback device or was there an icon with white X in red circle instead? Could you move the volume slider?

I find it hard to believe that it was caused by this particular tweak as it modifies only visual effects.

Could you please reapply `SetVisualFXAppearance` again to see if the problem still persist?

**Comment by murillow** [comment]
Honestly I can't replicate that problem too.

> How did it look like? Did you see a playback device or was there an icon with white X in red circle instead? Could you move the volume slider?

I did see my playback devices and also the Windows system audio was fine (for example, alerts and volume sliders). But I could not hear any application audio (for example, from Windows Media Player or from Google Chrome). To get application audio working again I had to switch back to `SetVisualFXAppearance`.

Maybe it was just some mistake on my part.
