### ISSUE TITLE
Any chance you'd covert most of this to Powershell DSC?

### ISSUE THREAD

**Issue by djdallmann** [Disassembler0/Win10-Initial-Setup-Script#191]
I recently made a powershell script that utilized powershell desired state configuration similar to what you have developed with regular powershell scripting interface. I built mine using process monitor to analyze modified registry keys by windows 10 guis, previous experience and some research.

The difference with DSC being is that you can check and enforce your systems state against a set of values quite trivially and dsc in general eliminates quite a large portion of scripting. There is a number of DSC features also in the powershell gallery for functions not supported out of the box.

https://docs.microsoft.com/en-us/powershell/dsc/overview/overview

Take a peek at my git and powershell dsc.
https://github.com/djdallmann/GamingPCSetup
https://github.com/djdallmann/GamingPCSetup/tree/master/PSDSC

**Comment by Disassembler0** [comment]
What benefits would it bring? I see only additional abstraction layer full of disadvantages.

- No possibility of copy-pasting and manually applying tweaks or portions of thereof.
- No possibility of effective maintenance of multiple presets and custom tweaks (DSC is not modular, it simply applies the whole structure, so modularity would have to be ensured by some external logic. Or by nesting or `Invoke-DscResource` which would complicate things even more.)
- No out-of-the-box support for scheduled tasks management, appx packages and some other stuff (defender, SMB, printers, ...). It would need to be handled by 3rd party DSC modules or by `Script` DSC objects.
- Tweaks with internal logic (build number checks, server checks or things like `UninstallOneDrive` or `UnpinStartMenuTiles`) would also need to be handled by `Script` invocation or split to individual parts. Many many maaaany individual parts.
- This is mostly personal feeling, but DSC is much less readable. Somehow I don't perceive writing a single registry key change to 5 lines instead of 1 as effective. It would make tweaks like `DisableAppSuggestions` a living hell.
- Last but not least, DSC requires Windows Remote Management (*WinRM*) service to be up and running which is something I would generally like to avoid on home devices.

DSC is good if you need to ensure that a bunch of remote computers will have the exact same configuration and that configuration will be kept over time and you can change it from a single place. But this isn't what my script is for.

You can of course give it a try and convert a few tweaks, but I'm pretty sure that at least 30% of the tweaks can't be converted while maintaining the simplicity and coherence. And you are of course more than welcome to push PRs or open issues for features which you're missing from my script. (I've seen several requests for the mouse sensitivity stuff which I see you have in yours, so that would be a nice one.)

**Comment by djdallmann** [comment]
Thanks for your reply and feedback, it sounds like you may have considered using it but decided not to due to the aforementioned roadblocks for your specific project. Plus you've already gone this far so it may take some time to rebuild or reimplement using a different method.

Cheers.
