### ISSUE TITLE
Suggestion: Change DNS to Cloudflare's

### ISSUE THREAD

**Issue by notcdk** [Disassembler0/Win10-Initial-Setup-Script#215]
I'd like to suggest to add an option that changes DNS to Cloudflare's https://1.1.1.1/
`Get-NetAdapter -Physical | Set-DnsClientServerAddress -ServerAddresses 1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001`

**Comment by AnubisMann** [comment]
> I'd like to suggest to add an option that changes DNS to Cloudflare's https://1.1.1.1/
> `Get-NetAdapter -Physical | Set-DnsClientServerAddress -ServerAddresses 1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001`

It is much better to always configure the DNS in the Router and not in the operating system. Configure the DNS within the router.

**Comment by notcdk** [comment]
> It is much better to always configure the DNS in the Router and not in the operating system. Configure the DNS inside the router.

Not if you are not connected to your home access point, or you simply just can't do that because it's automatically set.

**Comment by AnubisMann** [comment]
> > It is much better to always configure the DNS in the Router and not in the operating system. Configure the DNS inside the router.
> 
> Not if you are not connected to your home access point, or you simply just can't do that because it's automatically set.

Inside the router configuration set DNS manually. I have router and access point and it works perfectly with my DNS for all my devices and PCs....

**Comment by notcdk** [comment]
> Inside the router configuration set DNS manually. I have router and access point and it works perfectly with my DNS for all my devices and PCs....
Problem is some doesn't give that possibility, including mine.

**Comment by Disassembler0** [comment]
DNS setting is heavily a matter of personal preference and it's not just enable/disable as most of the tweaks in the script are. If I add CloudFlare, I may as well add Google, OpenDNS, Quad9 and others for people with different needs and preferences which is something I certainly don't want to do, mainly simply because it relies on 3rd party products and services.

This is a perfect example for a tweak to be added to [custom tweak library](https://github.com/Disassembler0/Win10-Initial-Setup-Script#advanced-usage) which are supported by the script.
