### ISSUE TITLE
Windows 10’s RAM Compression

### ISSUE THREAD

**Issue by Makxik** [Disassembler0/Win10-Initial-Setup-Script#232]
After I launched this preset (https://pastebin.com/wukgFnXx, release 3.6) Task Manager reporting 0 MB of memory usage every time. SysMain service is running. Fresh installation of Windows 10 (April 28). How to reenable this feature? (by default it using 15.3 MB)

**Comment by Disassembler0** [comment]
The compression is still enabled. You've just managed to optimize your system well enough, so it doesn't *need* to compress anything. The biggest contributors are `DisableBackgroundApps`, `UninstallMsftBloat` and `UninstallThirdPartyBloat` tweaks as they remove the ModernUI apps or block them from autostarting. ModernUI are the those which are normally suspended and compressed in RAM instead of being swapped out to disk.
