### ISSUE TITLE
Error 0x80D03002 installing games from the Microsoft Store.

### ISSUE THREAD

**Issue by AnubisMann** [Disassembler0/Win10-Initial-Setup-Script#281]
Hi,

When I want to install a microsoft game with active xbox game pass subscription, I get the error 0x80D03002 after using this script and it doesn't let me install any games.
How to revert to default windows values ?.

Thanks!

**Comment by Disassembler0** [comment]
I assume that `DisableXboxFeatures`, which is contained in the default preset, is the culprit. So try running `EnableXboxFeatures` to revert the Xbox-related tweaks.

**Comment by AnubisMann** [comment]
> I assume that `DisableXboxFeatures`, which is contained in the default preset, is the culprit. So try running `EnableXboxFeatures` to revert the Xbox-related tweaks.

Do not disable it, there is something else that is hurting.

**Comment by Disassembler0** [comment]
In that case please paste the preset you've used. It'll help us to narrow down possible causes.

**Comment by AnubisMann** [comment]
> In that case please paste the preset you've used. It'll help us to narrow down possible causes.


[Default.zip](https://github.com/Disassembler0/Win10-Initial-Setup-Script/files/3882906/Default.zip)

**Comment by AnubisMann** [comment]
> In that case please paste the preset you've used. It'll help us to narrow down possible causes.

Something new ?

**Comment by Disassembler0** [comment]
Your preset looks pretty safe. The only thing I particularly don't like is `SetP2PUpdateDisable`. Windows Store is incredibly stupid when it comes to selection of download mode and given what I've read online (e.g. [here](https://answers.microsoft.com/en-us/xbox/forum/all/xbox-pc-beta-erreur-0x80d03002/b14bc2b0-0e10-4aa6-af8f-3c32185a493a)) in relation to the error 0x80D03002, this may very well be the problem.

So instead of `SetP2PUpdateDisable` use rather `SetP2PUpdateLocal`.

Alternatively, delete the value `DODownloadMode` under `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization` via regedit (this is the same what `SetP2PUpdateLocal` would do) and then reboot.

**Comment by AnubisMann** [comment]
> Your preset looks pretty safe. The only thing I particularly don't like is `SetP2PUpdateDisable`. Windows Store is incredibly stupid when it comes to selection of download mode and given what I've read online (e.g. [here](https://answers.microsoft.com/en-us/xbox/forum/all/xbox-pc-beta-erreur-0x80d03002/b14bc2b0-0e10-4aa6-af8f-3c32185a493a)) in relation to the error 0x80D03002, this may very well be the problem.
> 
> So instead of `SetP2PUpdateDisable` use rather `SetP2PUpdateLocal`.
> 
> Alternatively, delete the value `DODownloadMode` under `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization` via regedit (this is the same what `SetP2PUpdateLocal` would do) and then reboot.

Thanks, it worked fine with the SetP2PUpdateLocal parameter.
Fixed !

**Comment by Cubox-** [comment]
I can confirm using SetP2PUpdateLocal fixed my issue with Xbox games for PC failing to install.
