### ISSUE TITLE
ShowQuickAccess in Explorer is not working

### ISSUE THREAD

**Issue by friki67** [Disassembler0/Win10-Initial-Setup-Script#294]
W10 1909 here. I think it could be

Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" -Name "HubMode" -Type DWord -Value 0

**Comment by Disassembler0** [comment]
Can't reproduce. Just tried it on 1909, build 18363.592 and both `HideQuickAccess` and `ShowQuickAccess` worked even without logoff. Make sure you run that tweak as an admin. If the problem persist, please paste the preset and command you're trying to run it with.

By default, the registry value is not set and the Quick Access is enabled. The script sets the "original" value, which in this case effectively means that it deletes it, rather than setting it to 0.
