### ISSUE TITLE
What are "ModernUI applications" - or how do I recognize them?

### ISSUE THREAD

**Issue by JustMyGithub** [Disassembler0/Win10-Initial-Setup-Script#327]
I expected that this is Windows Store only so I disabled Camera an Microphone access for it. However it seems that at least Zoom and Skype are Modern UI applications even in non-store versions

**Comment by guru-of-sound** [comment]
All apps will be Modern UI eventually.y. Its a xaml framework that Microsoft has been converting to.
https://docs.microsoft.com/en-us/windows/apps/winui/

**Comment by JustMyGithub** [comment]
Thank you for the reference. Why (do you state that) all app(lication?)s will be modern UI eventually? 

(Afaik "Apps" are small tools usually obtained from stores of ecosytems like Microsoft Store (UWP), Play Store (.apk) or Apple App Store (.ipa) and "Applications" are the classic desktop Win32 applications)

That seems quite pointless to me - From my understanding: If you want to be malware, you do not utilize Modern UI and all Modern UI restrictions will not hold for you. I also was surprised that there was no "xyz is trying to access your camera but this is disallowed by the current configuration"-type of message. Instead camera access was granted but only a static gray picture was shown.

Just let me encourage you to extend the comment on these features by a list of affected very popular applications, like non-store Skype and Zoom are. I think that would help other users to make a more informed decision and to not waste time to debug this issue like I did 😄

**Comment by Disassembler0** [comment]
The meaning just got lost in the evolution here. Originally, there were just the Win8 style *Metro UI* applications. Win10 introduced a concept which looked exactly the same for the end user, but Microsoft wanted to clearly communicate that it's not the same, so they called it *Modern UI*. The very first applications built on *Universal Windows Platform* (UWP) in 2015 and shipped with Win10 RTM all used this UI. The distinction between the platform and the UI wasn't that clear back then, so the script calls such apps *Modern UI* even though it's meant to be *UWP*, as UI is no longer a distinguishable feature. Most apps use Windows Presentation Foundation (WPF) for the UI which can look arbitrarily. UWP is just an API for the developers to use and the tweaks in question (resp. the Windows settings they set) control the use of the API. I'll amend the description of the tweaks.

> If you want to be malware, you do not utilize Modern UI and all Modern UI restrictions 

UWP is meant to be a simplification / unification for developers, not a security boundary. Although on platforms which allow installation of *only* UWP apps (Windows 10 S), it *could* be regarded as such, however [Microsoft doesn't consider even UAC a security boundary](https://techcommunity.microsoft.com/t5/windows-blog-archive/psexec-user-account-control-and-security-boundaries/ba-p/723551), so it's dubious. UWP is superset of several APIs, malwares don't need any of the functionality as they usually target a specific platform / architecture and specific vulnerability or bug (resp. feature :P ). Also, malwares usually don't have UI. If they do, oftentimes it's a custom UI, not using even Windows Forms. Also note that the tweaks in question are in *Privacy Tweaks* group, not in *Security Tweaks*. This is exactly because there is no guarantee that an application won't be able to use the respective devices, even though it's disabled by the settings.

As for the *how do I recognize them?* part - The app either uses Windows Forms UI, in which case it doesn't use UWP as these two are incompatible. Or it uses *some other* UI, in which case there's a good chance you're looking on WFP app, which also has a good chance to run on UWP. You can't be certain just by looking on it. I'm sure there are ways how to determine this programmatically, but I haven't had the need for it, so I can't be more specific.

**Comment by JustMyGithub** [comment]
Thank you again for the information. However with UWP in the documentation I (and probably many others) would even more expect that this is for store-apps only. If you google for what UWP is, you will find https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide as one of the first results. Yes, its two years old - but on that page Microsoft states that one of the features of UWP apps is their availability on the Microsoft Store. This maybe outdated information, but that is what users will find. 

> Just let me encourage you to extend the comment on these features by a list of affected very popular applications, like non-store Skype and Zoom are. I think that would help other users to make a more informed decision and to not waste time to debug this issue like I did 😄

But in the end it is your decision, of course.

**Comment by Disassembler0** [comment]
Hmm, the problem is actually elsewhere. On the current versions of Windows, there are 2 switches in camera and microphone privacy control panels. One for UWP and the other for desktop apps. Desktop apps can be disabled separately from UWP apps, but not vice versa. When UWP access is disabled, desktop apps are forcefully disabled along with it. So Zoom *is* a normal Win32 app, written in .NET Core, using WPF, but since it uses the proper Windows API for accessing the peripherals, it gets nothing because the access is blocked by the seemingly unrelated UWP settings. I'm almost sure it didn't work like this back in the days, but I'll amend the comments once more to remove the mention about UWP, since it disables camera and microphone access globally.

> I (and probably many others) would even more expect that this is for store-apps only.

It's similar to APK vs. Google Play - you're still free to create and install an application package from wherever, but the official distribution platform makes it easy to get the packages to the end users. This is also what the article you've linked says. It doesn't say anything about UWP being exclusively tied to Store. Initially, UWP was intended to be a prerequisite for acceptance into the Store, but Microsoft realized they'd have ridiculously low amount of applications there, so they allowed also classic Win32 apps and other stuff.

> list of affected very popular applications

I don't use any UWP apps, so I don't have any list. However there's a PR #315 which targets also UWP features, so I'm about to create a whole separate block for UWP tweaks where I'm about to briefly describe what UWP is. Nevertheless, it's now clear that the problem you've faced is unrelated to UWP.
