### ISSUE TITLE
Things that left after running script

### ISSUE THREAD

**Issue by Qrzysio** [Disassembler0/Win10-Initial-Setup-Script#38]
Hi,

thanks for the very great work!
I use your script since a few months and today I've tested the latest release on the very fresh Windows 10 Pro installation (the newest version - `1709/16299.15`).

Running your script was the absolutely the first thing I did after Windows was installed. I would like to share what left on the desktop/taskbar etc., which I thought your script will remove.

__Things/functions not changed__
- Edge icon is pinned to the taskbar,
- Windows Store icon is pinned to the taskbar (I don't want to remove the store, just remove unpin the icon from the taskbar),
- Lock screen is still active (have to press any key to see the PIN/password input) - I used `DisableLockScreenRS1` option and left `DisableLockScreen` commented,
- Xbox Live app is installed and Windows let us to uninstall it from Control Panel, so hopefully you can include it easily in the script.

**Comment by Disassembler0** [comment]
Hi,
- For pinning/unpinnig, see issue #8 . MS makes it very hard to get rid of tiles and pins, so it's unlikely such functionality will be in the script any time soon.
- `DisableLockScreenRS1` works only after lock or logout. After the computer starts, the lock screen is always there. Again a thing which MS enforces for Home and Pro. On Ent `DisableLockScreen` works without workarounds.
- Xbox Live app - OK, will check. Likely the app string has changed.

**Comment by Qrzysio** [comment]
Thank you.

Just want to make sure about lockscreen: From 1703 we should only use `DisableLockScreenRS1` option and leave `DisableLockScreen ` commented?

**Comment by Disassembler0** [comment]
> Just want to make sure about lockscreen: From 1703 we should only use DisableLockScreenRS1 option and leave DisableLockScreen commented?

This depends on the support of the `NoLockScreen` GPO.

On Enterprise, you can still use `DisableLockScreen` as the appropriate GPO setting is still supported there even in current builds.

On Home and Pro, the GPO setting is not supported since 1703, so you have to use the `DisableLockScreenRS1` which tries to work around the restriction imposed by Microsoft. As I said above, `DisableLockScreenRS1` is supposed to work for the screens you see after user locks / logs out, but doesn't work for the screen which you see right after startup.
