### ISSUE TITLE
Write-Output instead of Write-Host

### ISSUE THREAD

**Issue by swedishstyle** [Disassembler0/Win10-Initial-Setup-Script#44]
Sorry, I'm not really up on Github etiquette, so please let me know if this is the wrong place to put this.

I've noticed that all of your screen output uses the Write-Host cmdlet. Jeffrey Snover (inventor of PS) has written an article on the harmful consequences using write-host can cause: http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/

Very quick find->replace job, just thought I'd bring it up :)

**Comment by Disassembler0** [comment]
Even if it may not show, this is not my first PowerShell rodeo, so I'm aware about the contents of the linked article. I thought about which `Write-` to use before. The topic is still open for discussion, but consider these:

- First and foremost, it should be possible to use the script with the least effort possible. Since it's being used by unskilled BFUs for which even right-clicking and selecting *Run in PowerShell* is a complex task, `Write-Verbose` would either require manually entering the command or using `$VerbosePreference = "Continue"`. Moreover all messages are prepended by `"VERBOSE: "` string. This may be matter of personal preference, but I personally don't like it.
- It should be also possible to use the script as a base for provisioning automation and incorporate the functions into another PS script. Possible candidate would then be `Write-Output` but since the messages are intended to be informational for the *user*, redirecting such script to a log would eat them too. I'm aware about `Tee-Object` cmdlet but that doesn't help if the whole process output gets redirected. This again is a matter of personal preference, whether to "force" the information to show or whether to leave the decision on the downstream maintainer.

So I needed a `Write-` which would not be redirected but at the same time which would be always visible without any extraneous information or setting. Hence I got stuck with `Write-Host`.

What would your preference be and why?

**Comment by BlackDragonBE** [comment]
Just to chime in, I replaced all the Write stuff with Write-Output and it breaks the script, it just keeps asking for parameters now. Clearly it isn't just a case of find-replace.

**Comment by Disassembler0** [comment]
> Just to chime in, I replaced all the Write stuff with Write-Output and it breaks the script, it just keeps asking for parameters now. Clearly it isn't just a case of find-replace.

That's just the `Write-Host` without parameter in `WaitForKey` function. It can't handle colors either. Can be replaced with
```powershell
Function WaitForKey {
	Write-Output "`nPress any key to continue..."
	[Console]::ReadKey($true) | Out-Null
}
```
(Although this particular function won't be used in automation anyway due to the key press)

**Comment by swedishstyle** [comment]
My apologies, I never meant to call into question your Powershell knowledge - you clearly know your stuff!

I only decided to bring this up as a best practices type of deal, but it seems you've clearly thought hard about the consequences of each possibility. From your explanations, I'd tend to agree with your choice of Write-Host in this case, although I've only been using Powershell for about 1 year now, so my opinion may not be 100% valid :)

I've switched my copy of the script with Write-Output for my own consistency and fixed the WaitForKey issue, but for complete novice users, Write-Host will do the trick just fine.

Thank you for keeping this up to date and writing it in the first place - it's incredibly useful!
