### ISSUE TITLE
Mixed Reality App

### ISSUE THREAD

**Issue by rteischl** [Disassembler0/Win10-Initial-Setup-Script#46]
Hi,

great script, thanks for sharing! Will you also integrate a way for uninstalling/disabling Mixed Reality App?

**Comment by Disassembler0** [comment]
Nope, since it can't be uninstalled in similar fashion like the other applications.

Mixed Reality App is considered an essential app, same as e.g. Edge. There are ways how to get rid of them, but they are hacky and ugly. Since the Mixed Reality App is basically just first-run bootstrap, occupies cca 10 MB and does not have any running services or scheduled tasks, it's not worth the hassle.

If you'd find out an easy (and reversible) way how to get rid of it, feel free to reopen the issue and fill me in.
