### ISSUE TITLE
There's an option wich breaks windows update on a fresh Win10 Enterprise RS3 install

### ISSUE THREAD

**Issue by gladosfromaperturelabs** [Disassembler0/Win10-Initial-Setup-Script#57]
I don't know what is the option beacause I used the default ones plus others but this is the second time It happends to me with this script. I know this kind of stuff could be problematic, but I love the way this litle script can with an only click configure and debloat the whole OS.

Well, thanks for de PS Script. 
(... and sorry for my bad english).

:)

**Comment by Disassembler0** [comment]
How does it break the updates? What does it do when it's broken? Or what error message does it show?

**Comment by gladosfromaperturelabs** [comment]
I maked some tests on VMs, If I Disable Telemetry then the windows update only install one update and then it says there's more updates but never install them. I installed again in my real PC w/o using that option and the rest of the script works fine.

**Comment by vith** [comment]
Same here. The message was `Your device is at risk because it's out of date and missing important security and quality updates. Let's get you back on track so Windows can run more securely. Select this button to get going:` in the Windows Update screen of the Settings app. Clicking the button just results in the same message again.

Applying `EnableTelemetry` does successfully fix it without a reinstall.

**Comment by Disassembler0** [comment]
@vith: Thanks for the details. Do you also have Enterprise edition?

**Comment by vith** [comment]
Yep, version 1709

**Comment by Disassembler0** [comment]
The specific registry causing the problem is this one
https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/1eaa9d58bd50f5224f85249edecac91c09b2dffe/Win10.ps1#L153
However that's also integral part of why the tweak exists in the first place, so I'll probably just slap a warning there and try to get away with it. After all, if you're using Enterprise, chances are you have a domain GPO anyway as this isn't edition which you'd normally come by.
