### ISSUE TITLE
Can't get phone link to work

### ISSUE THREAD

**Issue by bustosalex** [Disassembler0/Win10-Initial-Setup-Script#61]
What do you I need to change or re-enable to get phone link to work again. I've attatched the changes I have made to the original script.
[Win10.txt](https://github.com/Disassembler0/Win10-Initial-Setup-Script/files/1805083/Win10.txt)

**Comment by Disassembler0** [comment]
If by *phone link* you mean something like `<a href="tel:555-555-5555">555-555-5555</a>`, then it should be opened in Skype by default. In your file I see you're reinstalling all the Microsoft software using `InstallMsftBloat` tweak (which, given all the surrounding tweaks, is a bit weird as on the clean installations you *already have* those apps). This also reinstalls the Skype and should make the links work again.

Since it seems that it's not the case for you, then you've probably done also some other actions apart from running the script. In this case, make sure that you have the Skype application installed (simply typing the name to start menu should show it) and then check if you have it associated with all protocols in *Settings* -> *Apps* -> *Default apps* -> *Set defaults by app* -> *Skype* -> *Manage* like this:

![skype](https://user-images.githubusercontent.com/5568046/37325320-b490f356-268d-11e8-8f60-d928aaf6d22c.PNG)
