### ISSUE TITLE
Small random suggestions

### ISSUE THREAD

**Issue by r3incarnat0r** [Disassembler0/Win10-Initial-Setup-Script#85]
I've been reviewing the script and stuff around and noticed some things that might deserve closer look. Probably no big deal mostly, some would be just cosmetics, some I'm not even sure about. :) But there it is anyway:

1) Make Default.preset and Default.bat linebreaks CRLF, so they can be edited in pure notepad. Other files are OK.
I created a number of custom presets by copying and editing Default.preset. Next day I needed to quickly edit one of them on some other PC using Widows' notepad and guess what problem occured. :) I didn't notice the problem before because I was preparing the presets in Kate on linux. :P Yes, I checked the original preset file so it's not like Kate screwed them.

2) Why using .bat extension instead of .cmd?
.bat = batch for 16-bit command.com DOS/Win9x
.cmd = batch for 32-bit cmd.exe NT+
There's no command.com in Win10. Yes, Win10 does not see difference anyway.

3) Sync disabled services with msconfig? So modifications can be seen and restored independently from there. Makes the tweaks bit longer. :(
```
# default value
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Shared Tools\MSConfig\services\ServiceName" -Name "ServiceName" -Type DWord -Value 3
# date changed (picked the "mysterious" date 6/21/2006 from windows generic drivers :)
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Shared Tools\MSConfig\services\ServiceName" -Name "YEAR" -Type DWord -Value 7D6
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Shared Tools\MSConfig\services\ServiceName" -Name "MONTH" -Type DWord -Value 6
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Shared Tools\MSConfig\services\ServiceName" -Name "DAY" -Type DWord -Value 15
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Shared Tools\MSConfig\services\ServiceName" -Name "HOUR" -Type DWord -Value 0
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Shared Tools\MSConfig\services\ServiceName" -Name "MINUTE" -Type DWord -Value 0
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Shared Tools\MSConfig\services\ServiceName" -Name "SECOND" -Type DWord -Value 0
```

4) SetCurrentNetworkPrivate should be #commented by default.
Setting network Private or Public is decision to be made depending on particular environment and imho should's be just blindly applied globally. Many users only need internet access so it's safer to stay in Public mode. This tweak exposes the system to the network.

5) Please split DisableThumbsDB and have available DisableThumbsDBOnNetwork separately.
IMHO:
Local DisableThumbsDB should be commented by default, many users have tons of folders with photos even on the Desktop, this just makes explorer keeping reloading thumbs over and over, slowing it down and wasting I/O.
On the other hand, DisableThumbsDBOnNetwork should be enabled by default, users keep bloating smb shares with annoying thumbs.db files, this madness must be stopped! :D

6) If DisableErrorReporting applied, shouln't be also service disabled?
Set-Service "WerSvc" -StartupType Disabled

7) DisableAutoLogger removed after 2.14, claiming not really useful.
You probably made more research than me, but wasn't the tweak broken just because these entries were not set?
```
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\WMI\AutoLogger\AutoLogger-Diagtrack-Listener" -Name "Start" -Type DWord -Value 0
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\WMI\AutoLogger\SQMLogger" -Name "Start" -Type DWord -Value 0
```

Thanks!

**Comment by Disassembler0** [comment]
That's a lot of points for one issue.

1. Right. That's what I get for trusting people doing the right thing in their PRs (#66) :( Will fix immediately.

2. Although you're right, there is no practical difference. For some reason, I learned to differentiate *.bat for non-interactive batch operations and *.cmd for interactive scripts. Since I'm touching the file in point 1 already, I can as well rename it.

3. I don't think so. If you stop and disable service manually via *Services*, this value doesn't get updated either. Furthermore, some AVs complain when you have msconfig in *Selective startup* which this addition would do.  
Slightly related to this point - Instead of checkboxes in msconfig, it would probably make more sense to set the GPO switches properly, so you'd see which exact policies are applied in *Group Policy Editor*, but I'm going to do that either.

4. *Many users* is a term relative to your use cases. My *many users* are all firewalled behind ISP-provided routers and always wondering why can't they see their computers from other devices in their home network. Once they move their laptop and connect to some other network which is potentially insecure, they will be prompted about the trustworthiness of the newly joined network (in which case they usually ignore the prompt and continue wondering :) ). That's why there is a separate tweak for the *current* network and for *all unknown* networks.  
It's impossible to have the defaults fitting for everybody. That's why there is the possibility to have your own preset and why the very first FAQ answer stresses to check the script before running. Originally, this script disabled also firewall and defender and most of the other security stuff which I personally don't use, so I think I have already made enough concessions in this matter.

5. Those are the same *many users* as in 4, aren't they? :) Alright, push a PR.

6. No need to. By default, this service is stopped and launched only on trigger. The GPO in `DisableErrorReporting` blocks the trigger.

7. See #20. I honestly don't even know where I got that tweak, but it probably was one of those paranoid sources where they were blocking disabling everything with slightly suspicious name. It wasn't broken. It was just useless because the log file is not generated even if the tweak is not used.

P.S.: Although I might seem dismissive in most points, I really like your thinking. Keep it up.
