### ISSUE TITLE
Sharing in lan network error 0x080070035

### ISSUE THREAD

**Issue by AnubisKerTV** [Disassembler0/Win10-Initial-Setup-Script#87]
After applying the Script I can not share content between two computers, I see the devices but when I want to enter it says:

the path to the network was not found
error 0x080070035

**Comment by Disassembler0** [comment]
I don't think this was caused by the script.

If you used the default preset, then the only tweaks which have anything to do with LAN settings and sharing are `SetCurrentNetworkPrivate`, which *enables* you to see the network devices and possibly `DisableAdminShares` which blocks access to the default hidden shares (like `\\HOST\C$`).

You can check some hints on how to deal with the error e.g. here - https://www.drivereasy.com/knowledge/error-code-0x80070035-the-network-path-was-not-found-solved/, but like I said, the script doesn't modify any of those things mentioned there.

And you can always revert all the applied tweaks using a custom preset. If you happen to find the tweak which you think may have caused this, let me know.

**Comment by CHEF-KOCH** [comment]
Not script related, see [here](https://www.reddit.com/r/Windows10/comments/8fogz8/windows_10_cannot_access_samba_share_0x800704b3/).

**Comment by AnubisKerTV** [comment]
Solved, the problem happens when you deactivate SMB1. With the default script everything works fine.

**Comment by CHEF-KOCH** [comment]
SMBv1 is by default already removed in recent Windows versions since 1607.
