### ISSUE TITLE
Windows Update Broken with telemetry disabled

### ISSUE THREAD

**Issue by T4CC** [Disassembler0/Win10-Initial-Setup-Script#92]
I know this bug was closed, and I posted this under the closed bug at first, then starting to think it might never be seen,  so decided to open a new bug for the same thing.  I'm sorry if it offends but I am also offering a better solution than just re-enabling telemetry.

If I am not mistaken, this bug goes back to 2015/16 Win 8/8.1, where disabling telemetry causes Windows Updates to go off the rails. I browse the various privacy script for updating my own and generally avoid any posting, but the least I can do is share a possible fix.  

In my own privacy script, Windows Update fails after disabling telemetry unless I add:
Path : hklm:\SOFTWARE\Policies\Microsoft\Windows\PreviewBuilds
ValueName : AllowBuildPreview
ValueType : DWord
Value : 0

Hopefully that helps.  There was more to the story under my original post, but the gist of it is that if you have preview builds enabled whether its Pro Enterprise, or maybe home (does anybody that can run a script even use that version?) you can't disable telemetry and get windows updates (usually) because you have expressly given them permissions to track your every waking moment in graphic detail...to fix their bugs of coarse, I'm sure nothing else. :)

**Comment by Disassembler0** [comment]
Hmm... So just to understand what's going on here - You're saying that if you completely remove the option to even enroll into the insider program (and download preview builds), the problem goes away?

I'm asking because I don't see the connection between these two. The only explanation with which I can come up now is that checking WU also tries to refresh some "insider initiation" package for which it needs the Telemetry data, which it doesn't have.

Anyway, I'll try to replicate the problem and then apply your suggestion. I'm really curious about this. Thanks for sharing.

**Comment by Disassembler0** [comment]
Aaaand it works. Awesome. Thanks again.

**Comment by T4CC** [comment]
NP,  Glad to help.

As you stated, from a technical standpoint there shouldn't be a connection.  But as an 'insider' you give them express permission to track you, and it therefore becomes a legal issue with a technical punishment if you don't.
